spring.application.name=web

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret-key=8f16548477592b7352d1392030e007e3edc59dfa9c7d3bfa45c669764eaf2755

jwt.expiration=900000